FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci
RUN npm exec prisma generate

COPY tsconfig.json ./
COPY src ./src

CMD ["npm", "run", "poll:prod"]
