export const unitTestFiles = [
  'src/incident-schema.test.ts',
  'src/incident-summary-fields.test.ts',
  'src/lib/aba-parser.test.ts',
  'src/lib/alert-summary-parser.test.ts',
  'src/lib/ebird-date-repro.test.ts',
  'src/lib/ebird-parser-robustness.test.ts',
  'src/lib/ebird-parser.test.ts',
  'src/lib/imap-client.test.ts',
  'src/lib/incident-service.test.ts',
  'src/lib/ingestion-orchestration.unit.test.ts',
  'src/lib/poller-runtime.test.ts',
  'src/lib/photo-policy.test.ts',
  'src/lib/poller-target-selection.test.ts',
  'src/lib/rarity-seeder.test.ts',
  'src/lib/rarity-service.test.ts',
  'src/lib/sighting-service.test.ts',
  'src/lib/sighting-observation-match.test.ts',
  'src/lib/streak-service.test.ts',
  'src/schema-check.test.ts',
  'src/test-msw.test.ts',
  'src/test/test-db-guard.test.ts',
];

export const smokeTestFiles = ['src/production-data.smoke.test.ts'];
