import { describe, it, expect } from 'vitest';
import { Prisma } from '@prisma/client';

describe('Prisma Schema Updates', () => {
  it('should have the new geospatial and eBird metadata fields in the Prisma client', () => {
    // This enum is generated by Prisma and should contain all model fields
    const sightingFields = Object.values(Prisma.SightingScalarFieldEnum);

    expect(sightingFields).toContain('latitude');
    expect(sightingFields).toContain('longitude');
    expect(sightingFields).toContain('subId');
    expect(sightingFields).toContain('locId');
    expect(sightingFields).toContain('speciesCode');
    expect(sightingFields).toContain('howMany');
  });

  it('should have the IncomingEmail model in the Prisma client', () => {
    // This will fail if the model is not in the schema and generated
    const emailFields = Object.values(Prisma.IncomingEmailScalarFieldEnum);

    expect(emailFields).toContain('id');
    expect(emailFields).toContain('messageId');
    expect(emailFields).toContain('rawBody');
    expect(emailFields).toContain('status');
  });

  it('should have the SpeciesPhoto model in the Prisma client', () => {
    // This will fail if the model is not in the schema and generated
    // @ts-expect-error - SpeciesPhotoScalarFieldEnum will not exist yet
    const photoFields = Object.values(Prisma.SpeciesPhotoScalarFieldEnum);

    expect(photoFields).toContain('speciesName');
    expect(photoFields).toContain('photoUrl');
    expect(photoFields).toContain('attribution');
    expect(photoFields).toContain('fetchedAt');
  });
});
