import { describe, it, expect } from 'vitest';
import { Prisma } from '@prisma/client';

describe('Prisma Schema Updates', () => {
  it('should have the new geospatial and eBird metadata fields in the Prisma client', () => {
    // This enum is generated by Prisma and should contain all model fields
    const sightingFields = Object.values(Prisma.SightingScalarFieldEnum);

    expect(sightingFields).toContain('latitude');
    expect(sightingFields).toContain('longitude');
    expect(sightingFields).toContain('subId');
    expect(sightingFields).toContain('locId');
    expect(sightingFields).toContain('speciesCode');
    expect(sightingFields).toContain('howMany');
  });
});
